### ISSUE TITLE
Didn't get a warning for not enough bright stars for ER?

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#113]
https://icxc.cfa.harvard.edu/aspect/SFE/2019/APR0819/prelim/APR0819P_sparkles/#id48265

I thought our simplified counting would still warn for fewer than three stars brighter than 9 (unless colder than .. -10.9?).  I assume the 9.05 is counting as a brighter than 9 in this case

```
HRC-S SIM-Z offset: 0.0 
ACA RA, Dec, Roll (deg): 204.26761 4.38465 171.00000 
Dither acq: Y_amp= 8.0  Z_amp=8.0 
Dither gui: Y_amp= 8.0  Z_amp=8.0 
Maneuver Angle: 43.76 Date: 2019:100:04:59:37.778  
idx slot    id    type  sz p_acq  mag  mag_err   yang    zang   row    col   dim res halfw 
--- ---- -------- ---- --- ----- ----- ------- ------- ------- ------ ------ --- --- -----   
1    0 40634792  BOT 8x8 0.975  8.81    0.07  -150.4  -144.5   36.2  -24.1  20   1   160   
2    1 40636024  BOT 8x8 0.761 10.07    0.15  1260.4 -1729.8 -248.2 -342.6  20   1    80   
3    2 40636360  BOT 8x8 0.822  9.79    0.17 -1877.4  1172.8  384.2  240.2  20   1   160   
4    3 40637152  BOT 8x8 0.779 10.11    0.15  -648.3  2064.7  137.3  420.0  20   1    60   
5    4 40637240  BOT 8x8 0.972  9.05    0.09     2.0  1266.3    6.2  258.9  20   1   160   
6    5 40637560  BOT 8x8 0.981  7.58    0.16  2361.9 -1545.9 -471.4 -306.4  20   1   160   
7    6 40766600  BOT 8x8 0.966  9.18    0.10 -2315.6 -2413.5  473.8 -484.4  20   1   160   
8    7 41026080  BOT 8x8 0.928  9.67    0.12  2407.3 -2418.8 -482.6 -484.3  20   1   160  

Probability of acquiring 2 or fewer stars (10^-x): 5.09 
Acquisition Stars Expected: 7.19 
Guide Stars count: 7.40 
Predicted Guide CCD temperature (max): -10.1 Predicted Acq 
CCD temperature (init) : -10.1
--
```

**Comment by taldcroft** [comment]
The computation is a smoothed version now.  I definitely expect that if you put that catalog into the function it will generate a number close to but > 3.0.  If not, that's a bug.  Otherwise, working as expected.

**Comment by jeanconn** [comment]
I still didn't think the smoothed version would do this.  Looks like you didn't get a warning on https://icxc.cfa.harvard.edu/aspect/SFE/2019/APR0819/prelim/APR0819P_sparkles/#id48248 either which is worse.  I'll review.

**Comment by jeanconn** [comment]
Ah, OK, so these just don't drop off nearly as fast as I thought they did and the new method is not as close as I thought to the old one.  Specifically,  the label  "count_9th: return fractional count of 9th mag or brighter stars" feels a little misleading when, say, at -9.9C a 9.2mag star is included in the sum as "half" of a bright star (the adjusted 9th limit is about 8.9mag == 1 star at -9.9C).

I think we may want the check to be more conservative for ERs than it is now then, but we can continue to watch this.  Thanks @taldcroft !
