### ISSUE TITLE
Optional use of OR list information

### ISSUE THREAD

**Issue by taldcroft** [sot/sparkles#122]
It would benefit ACA pre-review and review to have target info, mon window, etc from an OR list.  This would be fairly straightforward as an optional dependency.

**Comment by jeanconn** [comment]
OK.  I suppose for splits this works as they haven't been renumbered.  For pool targets and CCT targets I think there is nothing in the LTS OR, but maybe the help on the other observations is still worth it.

**Comment by jeanconn** [comment]
And useful to have warning or caution for Jupiter.

**Comment by jeanconn** [comment]
Idea is that the user would provide the pickle and the OR list.

**Comment by jeanconn** [comment]
OBE
