### ISSUE TITLE
Does not warn on bad class star added manually

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#132]
```
In [59]: kwargs
Out[59]:
{'att': <Quat q1=-0.37755625 q2=-0.74812491 q3=-0.54493232 q4=0.02844576>,
 'date': '2020:022:15:49:14.988',
 'detector': 'ACIS-S',
 'dither_acq': (7.9992, 7.9992),
 'dither_guide': (7.9992, 7.9992),
 'focus_offset': 0.0,
 'include_ids_guide': 257167016,
 'man_angle': 90.5221218316661,
 'n_acq': 8,
 'n_fid': 3,
 'n_guide': 5,
 'obsid': 22332.0,
 'sim_offset': 0.0,
 't_ccd_acq': -8.53046736331399,
 't_ccd_guide': -8.37963998295984}
```

```
In [50]: cat = proseco.get_aca_catalog(**kwargs)

In [51]: acar = cat.get_review_table()

In [52]: acar.run_aca_review()

In [53]: acar.messages
Out[53]: [{'category': 'warning', 'text': 'P2: 2.57 less than 3.0 for OR'}]
```

I would expect a warning from sparkles on the included guide star, as it is CLASS=3.  I think this is just a missing check and somewhat a proseco issue in that we had this idea that if you added it manually you knew what you were doing.  That is somewhat counter to the idea we had for checking stars for monitor->guide conversion IIRC on process.

**Comment by taldcroft** [comment]
Agreed we should issue a critical for CLASS != 0 in light of the monitor star conversion process.  It may just be that any guide star that does not meet the proseco criteria to be a candidate should get a critical which can be ignored if necessary.
