### ISSUE TITLE
Roll Suggestions Not Listing Viable Good Rolls

### ISSUE THREAD

**Issue by jayhead13** [sot/sparkles#138]
FOT MP has noticed that the Sparkles roll suggestions have been leaving out viable good rolls, as well as identifying a roll as bad even though it is actually good. Two examples are provided below.

**OBSID 22508 within the FEB1020 week ([FEB1020A.mat](https://occweb.cfa.harvard.edu/occweb/FOT/mission_planning/temp/FEB1020A.mat)):**
- Nominal Roll of ~161.1343 ([Sparkles report for nominal roll](https://occweb.cfa.harvard.edu/occweb/FOT/mission_planning/temp/FEB1020_22508_Sparkles_Suggestion_NO_ROLL.PNG))
- No suggested rolls provided by Sparkles while at nominal roll
- Attempting a nearby roll of 160 degrees provides a suitable catalog that passes Sparkles checks ([Sparkles report for this roll](https://occweb.cfa.harvard.edu/occweb/FOT/mission_planning/temp/FEB1020_22508_Sparkles_Suggestion_160_SUGGESTED_ROLL.PNG))

~~**OBSID 22333 within the FEB1720 week ([FEB1720B.mat](https://occweb.cfa.harvard.edu/occweb/FOT/mission_planning/temp/FEB1720B.mat)):**~~
- *From @jayhead13: "I'm not able to reproduce this bug anymore either, even when using an archived 2019_210 version of MATLAB Tools."*
- Nominal Roll of ~213.8776 ([Sparkles report for nominal roll](https://occweb.cfa.harvard.edu/occweb/FOT/mission_planning/temp/FEB1720_22333_Sparkles_Suggestion_NO_ROLL.PNG))
- Multiple rolls suggested by Sparkles, all of which contain critical errors
- Attempting one of the suggested rolls (201.7526) provides a suitable catalog that passes Sparkles checks even though Sparkles originally reported that roll would contain critical errors ([Sparkles report for this roll](https://occweb.cfa.harvard.edu/occweb/FOT/mission_planning/temp/FEB1720_22333_Sparkles_Suggestion_201_7526_SUGGESTED_ROLL.PNG))

**Comment by taldcroft** [comment]
@jayhead13 - thanks for the detailed report, will look into this.

Maybe it is time to push forward with #106, the brute-force approach of uniformly sampling the entire roll range.  This could take a minute or two but that will likely be faster in the end for troublesome cases.
