### ISSUE TITLE
Provide target offset to proseco or sparkles

### ISSUE THREAD

**Issue by taldcroft** [sot/sparkles#141]
I believe the source of the issue for obsid 22333 in #138 is that sparkles is not being made aware of the target offset, so it is rolling around assuming TARGET_OFFSET=(0, 0).  For obsid 22333 it is actually TARGET_OFFSET=(-0.033333,0.000000). Information about the offset needs to be provided at some point:
- When getting the initial catalog with `get_aca_catalog(..., target_offset_y=..)`
- When creating the AcaReviewTable object (e.g. `aca.get_review_table(target_offset_y=...)`
- When running the review (`acar.run_aca_review`)

The best would be the first so that the target offset gets into the pickle.

This also relates to #122 to include other information from the OR list so facilitate ACA pre-review (target name would be especially useful).

cc: @jayhead13 @jskrist

**Comment by jskrist** [comment]
Should the target offset be passed in via two separate keyword args, i.e. ```target_offset_y``` and ```target_offset_z```, or as a single list, e.g. ```target_offset = [target_offset_y, target_offset_z]```?

**Comment by jeanconn** [comment]
Also, I think this relates more to #262 than #122.  I thought #122 was about using the OR list file "on the side" to help out until values could be supplied from the ORViewer side.

**Comment by jskrist** [comment]
@jeanconn, I had forgotten about sot/proseco#262.  It seems like there are several issues all related to the same thing here (#138, sot/sparkles#141, sot/proseco#262, sot/proseco#304, sot/proseco#305).  would it make sense to consolidate them into a single issue, or do they each serve a unique enough purpose?

I see each of these as being special cases of something like "standardize the proseco-MATLAB interface" or "pass relevant data between MATLAB and proseco".

**Comment by taldcroft** [comment]
👍 I'll try to consolidate. The only one in your list that is not simply a variant of the proseco-MATLAB interface is #138, which is partly due to incomplete information but also relates to a real deficiency in the algorithm.

**Comment by jeanconn** [comment]
Yes, though per the meeting I was thinking of them really as the *two* MATLAB issues, the "ORViewer passes useful OR information to proseco" issue (which is basically  https://github.com/sot/proseco/issues/262 ) and the "MATLAB should rely entirely on proseco catalog for uplinked catalog values" https://github.com/sot/proseco/issues/304 . I think the others still might deserve issues on this side (using target offsets for roll determination and handling monitor window stuff is separate conceptually) but shouldn't need matlab.

**Comment by taldcroft** [comment]
> Should the target offset be passed in via two separate keyword args, i.e. target_offset_y and target_offset_z, or as a single list, e.g. target_offset = [target_offset_y, target_offset_z]?

Whatever is more convenient.  There is precedent for passing `dither` as a 2-component, so that would be the preference.

**Comment by jeanconn** [comment]
Resolved in matlab tools 2022_030
