### ISSUE TITLE
Not clear which guide_count is required

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#22]
Does aca_preview 4.0 require chandra_aca with https://github.com/sot/chandra_aca/pull/71 ?  Or is it OK to not use the interpolated fractional count in the 4.0 release?  Or should the interpolated fractional count be added as a method in aca_preview which will reduce scope.

Note that changing the chandra_aca guide count in the installed release would change thumbs_up in proseco as well.

**Comment by taldcroft** [comment]
I think we should NOT include the chandra_aca update in this release.  That definitely increases scope and I'm not comfortable with the review of that scope change given the compressed time frame.

**Comment by jeanconn** [comment]
Great.  I'm :+1: on that.

**Comment by jeanconn** [comment]
Is now planned to be chandra_aca 4.25.1 for sparkles 4.1 release.
