### ISSUE TITLE
Readability tweak for mag column in report?

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#23]
I think I could use a couple of additional spaces before the 'mag' column in the catalog display.  I keep scanning the 'maxmag' column as mag by accident because it is set off more by space (mostly due to the length of 'maxmag' > 'mag').

**Comment by jeanconn** [comment]
Reminds me that I would actually like POS_ERR in the guide reporting, but it can probably wait.

**Comment by jeanconn** [comment]
Also 'mag' may now be the only column that is changing width, so having a fixed with would not be a disaster ...

**Comment by taldcroft** [comment]
Not sure what that means.

**Comment by jeanconn** [comment]
I just mean mag gets more room for a catalog with one 10.00 mag star or fainter, and suddenly becomes more readable to me for most of the entries.

**Comment by taldcroft** [comment]
aca_preview 4.1

**Comment by jeanconn** [comment]
Fair enough.

**Comment by jeanconn** [comment]
I don't think #26 closed this.

With regard to readability, I'd also prefer 'idx' before 'slot' in the reports.
