### ISSUE TITLE
Writes out to directory of pkl file

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#27]
When I called the tool on a pkl file, I was surprised that the tool wrote out to the directory containing that file and not to my working directory.

**Comment by taldcroft** [comment]
That doesn't surprise me.  You can you `--outdir`.

**Comment by jeanconn** [comment]
Sure.  Not considering it a bug and makes sense in 

https://github.com/sot/aca_preview/blob/ce546ded49f7900fbac2add45ed3cc33400e7fd0/aca_preview/preview.py#L130

I had just figured it would use file basename when inferring load_name.  Anyway I mostly meant this as a note for us for a common use case (calling tools on files in /data/mpcrit1/mplogs), so will need outdir if working on a file in a non-owned directory.

**Comment by jeanconn** [comment]
Closed by #57
