### ISSUE TITLE
Change ER guide stars: only 6 stars from critical to warning

### ISSUE THREAD

**Issue by taldcroft** [sot/sparkles#36]
The message "ER guide stars: only 6 stars" is critical.  Maybe this should be a warning (preference) since it does meet the ACA-008 checklist requirement.

**Comment by jeanconn** [comment]
Maybe?  I coded these up quickly wondering if at this point in the mission we really did have an implicit requirement that ERs have 8 guide stars (in addition to the explicit require that there are at least 3 9th or brighter ones).  Fine to demote a 6 or 7 guide star case to warning.  Would we critical warn on 5 guide stars? (doesn't really meet checklist requirements at that point)

**Comment by taldcroft** [comment]
Yes, critical at 5, warn at 6.
