### ISSUE TITLE
Should we keep orange warning for guide stars within 5 pixels of the padded edge?

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#41]
Proseco selection will fix the critical warnings for within 2.5 pixels of the edge because selection will be forbidden within 3 pixels of the padded edge.  Then does the orange warning on < 5 really have value?  Should it really drive star edit or roll change as a preference?

**Comment by taldcroft** [comment]
How about we downgrade to `info` for now just to keep a little visibility into close-to-the-edge stars.

**Comment by jeanconn** [comment]
Sounds good!
