### ISSUE TITLE
Roll Options misreporting/miscalculating messages

### ISSUE THREAD

**Issue by jskrist** [sot/sparkles#66]
When an ER (and maybe an OR, but I haven't confirmed it) has roll_options calculated for it, the messages in the roll_options (e.g. acar.roll_options["aca"].messages) do not match the acar.messages.  Specifically, I have seen **Critical** messages become _Warning_ messages:

from the main report:
![image](https://user-images.githubusercontent.com/991715/53046236-9c46cf80-345d-11e9-9dc9-2dfa1cc84ca7.png)
from the roll_options report:
![image](https://user-images.githubusercontent.com/991715/53046281-b2549000-345d-11e9-82f9-bc58b3d54e25.png)
Note that the last _Warning_ was a **Critical** message in the main report.

and other times the **Critical** messages seem to disapear:
from the main report:
![image](https://user-images.githubusercontent.com/991715/53045821-98667d80-345c-11e9-942a-02b69ab778bf.png)
from the roll_options report:
![image](https://user-images.githubusercontent.com/991715/53046186-7d483d80-345d-11e9-92b5-410963992d45.png)

**Comment by jeanconn** [comment]
Looks like the issue is that it can't decide if it is an ER or an OR.

**Comment by taldcroft** [comment]
Looks like the catalog is being interpreted as an OR instead of ER.  This should be easier to track down...  :smile:
