### ISSUE TITLE
Should probably add something to check to see if plots need to be remade

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#81]
The MAR0419 second prereview has at least one starcat plot that doesn't match the catalog.  My best guess is that the tool was run more than once on a pickle file of the same name (but with different catalogs) and that the line here:

https://github.com/sot/sparkles/blob/ee9455adc4034932cfdc693db0f4a0afb813bdde/sparkles/core.py#L600

kept the catalog that had actually changed from making a new plot.  If that line is there as an optimization to make sure we don't keep making plots gratuitously, we probably need something (file saved sha of catalog?) to check before deciding if the plot gets remade or not.  I assume this could also be an issue in the view-the-html reporting from ORViewer (will the catalog plots actually get remade after an edit?  That was really the only use case I put forward at the working group).

**Comment by taldcroft** [comment]
Yeah why don't you do a quick practice to chop that.  this was pretty helpful during heavy development but I agree it doesn't belong in the production code.

**Comment by jeanconn** [comment]
OK.  Just remaking all the catalog plots is a simpler plan and they aren't big :+1:
