### ISSUE TITLE
remove test() calls in release code

### ISSUE THREAD

**Issue by jskrist** [sot/sparkles#88]
https://github.com/sot/sparkles/blob/9f330762c485e088fc5a16ebdecff82d87ada56e/sparkles/core.py#L36

This code causes a dialog to flash in Windows, which is undesirable for the release.

**Comment by taldcroft** [comment]
I don't know why this didn't auto close, maybe because I merged to 4.1.x not master?

**Comment by jeanconn** [comment]
Yeah, I think github says the issue needs to merge into the "default" branch to auto close.  We could actually change 4.1.x to be the default branch if we anticipated a slew of bugfixes.

**Comment by taldcroft** [comment]
Now that I'm sure about this behavior, in the future I will go the normal route and merge to master and cherry-pick to the branch.  Lesson learned.
