### ISSUE TITLE
Cluster warning indexes are slots?

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#98]
In 

https://icxc.cfa.harvard.edu/aspect/SFE/2019/MAR0419/oflsa/MAR0419A_sparkles/index.html#id21150

the cluster warning 
```
>> CRITICAL: Guide indexes (4, 5, 7) clustered within 500" radius
```
Looks to be on slots 4, 5, 7, indexes 5, 6, and 8.  So that's a little confusing.

**Comment by taldcroft** [comment]
Actually it's just an off-by-one.  There is an unfortunate overlap of `idx` as the "idx" column that starts with 1 and the `idx` into the table rows which starts with 0.

**Comment by jeanconn** [comment]
Right, I didn't dig into the code and just plopped this up as I saw it.

**Comment by taldcroft** [comment]
For the next release we might consider start the catalog idx at 0.  This is an easy pathway to bugs.
